function involute_rack_tooth_profile(m, pa = 20, clearance = undef) = //! Calculate rack tooth profile given module and pressure angle
    let(p = PI * m,                                     // Pitch
        ha = m,                                         // Addendum
        c = is_undef(clearance) ? m / 4 : clearance,    // Tip root clearance
        hf = m + c,                                     // Dedendum
        hw = 2 * m,                                     // Working depth
        h = ha + hf,                                    // Tooth depth
        crest_w = p / 2 - 2 * ha * tan(pa),             // Crest width
        base_w = crest_w + 2 * hw * tan(pa),            // Base width
        root_w = p - base_w,                            // Root width
        clearance_w = root_w - 2 * c * tan(pa),         // Width of clearance without fillet
        kx = tan(pa / 2 + 45),                          // Fillet ratio of radius and xoffset
        pf = min(0.38 * m, kx * clearance_w / 2),       // Dedendum fillet radius
        x = pf / kx,                                    // Fillet centre x offset from corner
        sides = ceil(r2sides(pf) * (90 - pa) / 360),    // Fillet facets taking $fa, $fs and $fn into account
        fillet = [ for(i = [0 : sides - 1], a = i * (90 - pa) / sides + 270) [clearance_w / 2 - x,  -hf + pf] + pf * [cos(a), sin(a)] ],
        reflection = reverse([for(pt = fillet) [p - pt.x, pt.y] ]) // reflect for trailing edge
    ) concat(fillet, [ [root_w / 2, -hw / 2], [p / 2 - crest_w / 2, ha], [p / 2 + crest_w / 2, ha], [p - root_w / 2, -hw / 2] ], reflection);