def generate_code(prompt, context=None):
    """
    Generate OpenSCAD code from a prompt using a local LLM.
    Optionally use context (from RAG).
    """
    # TODO: Integrate with local LLM (Ollama, llama.cpp, etc.)
    return "// OpenSCAD code generated by local LLM" 